FROM golang:alpine as build-env

ENV GO111MODULE=on

RUN apk update && apk add bash ca-certificates git gcc g++ libc-dev

WORKDIR /go/src/poc_team1 

COPY . /go/src/poc_team1

WORKDIR /go/src/poc_team1/client

RUN go build -o client client.go 

CMD "./client"